ARG DOCKER_HUB
ARG CSI_SNAPSHOT_CONTROLLER_VERSION

FROM ${DOCKER_HUB}/sig-storage/snapshot-controller:${CSI_SNAPSHOT_CONTROLLER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
