ARG DOCKER_HUB
ARG NVIDIA_DCGM_EXPORTER_VERSION
FROM ${DOCKER_HUB}/nvidia/k8s/dcgm-exporter:${NVIDIA_DCGM_EXPORTER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
