ARG DOCKER_HUB
ARG VSPHERE_CPI_MANAGER_VERSION
FROM ${DOCKER_HUB}/cloud-provider-vsphere/cpi/release/manager:${VSPHERE_CPI_MANAGER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
