ARG DOCKER_HUB
ARG MEMCACHED_EXPORTER_VERSION
FROM ${DOCKER_HUB}/prometheus/memcached-exporter:${MEMCACHED_EXPORTER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
