ARG DOCKER_HUB
ARG VELERO_PLUGIN_GCP_VERSION

FROM ${DOCKER_HUB}/velero/velero-plugin-for-gcp:${VELERO_PLUGIN_GCP_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
