ARG DOCKER_HUB
ARG BITNAMI_KUBEAPPS_ASSETSVC_VERSION

FROM ${DOCKER_HUB}/bitnami/kubeapps-assetsvc:${BITNAMI_KUBEAPPS_ASSETSVC_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
