ARG DOCKER_HUB
ARG BITNAMI_KUBEAPPS_APIS_VERSION

FROM ${DOCKER_HUB}/bitnami/kubeapps-apis:${BITNAMI_KUBEAPPS_APIS_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
