ARG DOCKER_HUB
ARG VAULT_CSI_PROVIDER_VERSION
FROM ${DOCKER_HUB}/hashicorp/vault-csi-provider:${VAULT_CSI_PROVIDER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
