ARG DOCKER_HUB
ARG GITLAB_AGENTK_VERSION
FROM ${DOCKER_HUB}/gitlab-org/cluster-integration/gitlab-agent/agentk:${GITLAB_AGENTK_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
