ARG DOCKER_HUB
ARG VELERO_PLUGIN_AWS_VERSION

FROM ${DOCKER_HUB}/velero/velero-plugin-for-aws:${VELERO_PLUGIN_AWS_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
