apiVersion: v1
entries:
  keda:
  - apiVersion: v2
    appVersion: 2.9.3
    created: "2023-03-11T18:00:12.196626+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: c455dc8d908b6e8575fe0dbe8275861355cb242a5768f23cd909e543fe077438
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.9.4.tgz
    version: 2.9.4
  - apiVersion: v2
    appVersion: 2.9.2
    created: "2023-03-11T18:00:12.193212+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 52a5de6f5585fb2cfe44ba9ddadcf4cd4208138795313e25ee654d82a424faef
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.9.3.tgz
    version: 2.9.3
  - apiVersion: v2
    appVersion: 2.9.2
    created: "2023-03-11T18:00:12.190368+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: a1f14048f1788cde92a42412fa789e34d48bb4a8e94d4b43e0c70c8b8c326e43
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.9.2.tgz
    version: 2.9.2
  - apiVersion: v2
    appVersion: 2.9.1
    created: "2023-03-11T18:00:12.186878+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 004f2f37845a324badc7228585755ddfd8f5feea957cdca7de9b39499ce1a8d8
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.9.1.tgz
    version: 2.9.1
  - apiVersion: v2
    appVersion: 2.9.0
    created: "2023-03-11T18:00:12.183806+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: e0f84de35c0378027f43a732f12a164db05e45947687203020c0031baeee5826
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.9.0.tgz
    version: 2.9.0
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2023-03-11T18:00:12.180028+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: bbd9f4f9312781de5363145d5a937d7c084ea1139f12f5e7f153b3f174332517
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.8.4.tgz
    version: 2.8.4
  - apiVersion: v2
    appVersion: 2.8.2
    created: "2023-03-11T18:00:12.177224+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 04934ca1e41970ca687de13db697cc7fdc24d367af570eba47bed01ad981e1b1
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.8.3.tgz
    version: 2.8.3
  - apiVersion: v2
    appVersion: 2.8.1
    created: "2023-03-11T18:00:12.173068+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: e7bc80a5dde861a5f62b73e9d5c4ce139339b07438344668485fdc435f3109b4
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.20.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.8.2.tgz
    version: 2.8.2
  - apiVersion: v2
    appVersion: 2.8.0
    created: "2023-03-11T18:00:12.169636+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: df15ce1a4a27df2f3eb85c7cc803de53dec526bcad92d732a0944bd5288f4845
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.8.1.tgz
    version: 2.8.1
  - apiVersion: v2
    appVersion: 2.8.0
    created: "2023-03-11T18:00:12.165249+01:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: afa9410e4e6e805979e5c22a17db6dc7dc2720c28b3f176d2eef2708ef0d0a32
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.17.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.8.0.tgz
    version: 2.8.0
generated: "2023-03-11T18:00:12.16171+01:00"
