apiVersion: v1
entries:
  keda:
  - apiVersion: v2
    appVersion: 2.15.0
    created: "2024-08-04T20:01:56.781128+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: fbcbdaa0242edf90040ac932e01e61f1ebde42e5ae9c90e75fe6ae57bc64d8ba
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.15.0.tgz
    version: 2.15.0
  - apiVersion: v2
    appVersion: 2.14.1
    created: "2024-08-04T20:01:56.773631+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 6d1a68d143bc9e184dfe1945097ba2c4e0a3fb81be8a78115138e9c08d311e8e
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.14.3 copy.tgz
    version: 2.14.3
  - apiVersion: v2
    appVersion: 2.14.0
    created: "2024-08-04T20:01:56.761098+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: e1d477d173305aa41d1ac4f6a07e6ff48a3b5bf8e35a74fdf9da1f30b8f97355
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.14.2.tgz
    version: 2.14.2
  - apiVersion: v2
    appVersion: 2.14.0
    created: "2024-08-04T20:01:56.750124+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 8ad2f13172e1e38b96a3ff8e8737137e2c43026354b3c4ac4fb2e51bccdeb213
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.14.1.tgz
    version: 2.14.1
  - apiVersion: v2
    appVersion: 2.14.0
    created: "2024-08-04T20:01:56.744372+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: bdd669a80a8bc9d1e651b7680f4227cbc374a861e89c0ed3120e328b4aacfd39
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.14.0.tgz
    version: 2.14.0
  - apiVersion: v2
    appVersion: 2.13.1
    created: "2024-08-04T20:01:56.737398+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 3d1bb0537755ebeafacf1da9f91fbcbbac7b673b0e4141cc827e32635e68c228
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.13.2.tgz
    version: 2.13.2
  - apiVersion: v2
    appVersion: 2.13.0
    created: "2024-08-04T20:01:56.729843+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 00ae78109f89f16b12bb5cf23f7071c6c2fe09294514d4f7fd3850c6ce2b8a57
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.13.1.tgz
    version: 2.13.1
  - apiVersion: v2
    appVersion: 2.13.0
    created: "2024-08-04T20:01:56.722915+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 0dcc74315d6ca02fbadcfc5e358040580c0ad7919921e07ebf2dcc0b1d2d5f03
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zbynek@kedify.io
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.13.0.tgz
    version: 2.13.0
  - apiVersion: v2
    appVersion: 2.12.1
    created: "2024-08-04T20:01:56.715998+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: ee87da063be94f3f65661656602775c38ab723374c9892ecc73c1cea269e64c0
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.12.1.tgz
    version: 2.12.1
  - apiVersion: v2
    appVersion: 2.12.0
    created: "2024-08-04T20:01:56.70803+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 5ae5ef24c2e4c38450bb31b7987aea8b19a828c0c6cfa66b8e7ffbc65ebf164d
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.12.0.tgz
    version: 2.12.0
  - apiVersion: v2
    appVersion: 2.11.2
    created: "2024-08-04T20:01:56.70187+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 1fc274ebf7c405031297166fa3295f13bc9470f3ca688d595b7549d072b062cd
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.11.2.tgz
    version: 2.11.2
  - apiVersion: v2
    appVersion: 2.11.1
    created: "2024-08-04T20:01:56.695976+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 7d10ab788d363c95f496f28d48a74ab7789a5d04c63d9fa3e5d55967c988c0ed
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.11.1.tgz
    version: 2.11.1
  - apiVersion: v2
    appVersion: 2.11.0
    created: "2024-08-04T20:01:56.690263+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 8a2100ac1c47053e118b177676fbc07fe427fb9878c31ee7f8b73df0e2a77a06
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.23.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.11.0.tgz
    version: 2.11.0
  - apiVersion: v2
    appVersion: 2.10.1
    created: "2024-08-04T20:01:56.684965+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 2e75903cda0780a4a8115dc199541315eaccdbfc3ec3da5ab492c8825080cc99
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.24.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.10.2.tgz
    version: 2.10.2
  - apiVersion: v2
    appVersion: 2.10.0
    created: "2024-08-04T20:01:56.67908+02:00"
    description: Event-based autoscaler for workloads on Kubernetes
    digest: 7216ff7cff5567152b895017b97a95b41b788589c4be82169d92906519a24f25
    home: https://github.com/kedacore/keda
    icon: https://raw.githubusercontent.com/kedacore/keda/main/images/keda-logo-500x500-white.png
    kubeVersion: '>=v1.24.0-0'
    maintainers:
    - email: ahmels@microsoft.com
      name: Ahmed ElSayed
    - email: jorge_turrado@hotmail.es
      name: Jorge Turrado
    - email: kerkhove.tom@gmail.com
      name: Tom Kerkhove
    - email: zroubali@redhat.com
      name: Zbynek Roubalik
    name: keda
    sources:
    - https://github.com/kedacore/keda
    urls:
    - keda-2.10.1.tgz
    version: 2.10.1
generated: "2024-08-04T20:01:56.673021+02:00"
