ARG DOCKER_HUB
ARG GITLAB_AUTO_BUILD_VERSION
FROM ${DOCKER_HUB}/gitlab-org/cluster-integration/auto-build-image:${GITLAB_AUTO_BUILD_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
