apiVersion: v1
entries:
  akv2k8s:
  - apiVersion: v2
    appVersion: 1.7.3
    created: "2024-11-02T14:14:31.056712+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 499f82dabbcefd0df032baeeaa6cf817a8b9f39baa08c16c6363b99d58951006
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.7.2.tgz
    version: 2.7.2
  - apiVersion: v2
    appVersion: 1.7.1
    created: "2024-11-02T14:14:31.055994+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 8e167122407ebe8b7021ca01b733a4b77de98848184ddbd5e2a6b9a338ed3d38
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.7.1.tgz
    version: 2.7.1
  - apiVersion: v2
    appVersion: 1.7.0
    created: "2024-11-02T14:14:31.054855+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 439bec04113f8cdfd01859902e3cb747945d2b9ca652338d2252bafce3621226
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.7.0.tgz
    version: 2.7.0
  - apiVersion: v2
    appVersion: 1.6.0
    created: "2024-11-02T14:14:31.054057+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: b4e67c9362d95066a4d4eedc5fee6b279b3e8b12f9feda8f104148fbee08cfe3
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2024-11-02T14:14:31.053258+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: e5343599e97250cf3c017a05b90cadfa562f5eef509153ddd01afd3d3c46d42b
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.5.1.tgz
    version: 2.5.1
  - apiVersion: v2
    appVersion: 1.5.0
    created: "2024-11-02T14:14:31.052468+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 37c912792d568432df91c4f01d6050600f73ab868a8b05a8619e60115e5270db
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-11-02T14:14:31.051611+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: c1f7ab7adf08a98b5013d2a61e7ddb08424605238b7090799ef8d3f2b1675278
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.4.2.tgz
    version: 2.4.2
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-11-02T14:14:31.050874+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 3aae754c96065af0ef55616361a7e93313d615d8eedabcdfaa910852d6800bc8
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.3.5.tgz
    version: 2.3.5
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-11-02T14:14:31.04963+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 9824f74cc5b80c9504f95a23d9c022e58b3dc68a3a477abb1059f22af4ab4a74
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.3.4.tgz
    version: 2.3.4
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-11-02T14:14:31.048679+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 05d1597446a53549fb6be0f8402b47498d899ac58732d9f92314d288875d637a
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.3.2.tgz
    version: 2.3.2
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-11-02T14:14:31.047939+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: cf2791d981ab1a99313067c554afef4d70061e3574b4178d42916366d0597ebd
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.3.1.tgz
    version: 2.3.1
  - apiVersion: v2
    appVersion: 1.4.0
    created: "2024-11-02T14:14:31.047149+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: a03f8109838f379fb7cce812a5d55a94a9fc83dd07c437df379b281d5ba4c061
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 1.3.1
    created: "2024-11-02T14:14:31.046169+01:00"
    description: A Helm chart that deploys akv2k8s Controller and Env-Injector to
      Kubernetes
    digest: 301dfea635db5e5b1428f1c1b5ee22314ff37f5757af120216b79a2ad16a5405
    icon: https://raw.githubusercontent.com/SparebankenVest/azure-key-vault-to-kubernetes/master/akv2k8s_small.png
    maintainers:
    - email: jon@torresdal.net
      name: Jon Arild Tørresdal
      url: https://mrdevops.io
    name: akv2k8s
    urls:
    - akv2k8s-2.2.2.tgz
    version: 2.2.2
generated: "2024-11-02T14:14:31.045175+01:00"
