ARG DOCKER_HUB
ARG BITNAMI_SEALED_SECRETS_CONTROLLER_VERSION
FROM ${DOCKER_HUB}/bitnami/sealed-secrets-controller:${BITNAMI_SEALED_SECRETS_CONTROLLER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
