name: archive
on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Archive mode (upstream or complete)'
        required: true
        default: 'upstream'
        type: choice
        options:
          - upstream
          - complete
      version:
        description: 'Version to archive (leave empty for last tag)'
        required: false
        type: string
      batch_size:
        description: 'Batch size'
        required: false
        default: '10'
        type: string

env:
  IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY || 'cr.noroutine.me' }}

jobs:
  archive-images:
    name: archive-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for tags

      - name: Determine version
        id: version
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            # User specified version
            VERSION="${{ github.event.inputs.version }}"
          else
            # Get last tag
            VERSION=$(git tag --sort=-version:refname | head -n 1)
            if [[ -z "$VERSION" ]]; then
              echo "No tags found, using current commit"
              VERSION=$(git rev-parse --short=8 HEAD)
            fi
          fi

          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Archive version: ${VERSION}"

      - name: Setup Docker config
        run: |
          mkdir -p ~/.docker
          echo "${{ secrets.DOCKER_CFG }}" | base64 -d > ~/.docker/config.json

      - name: Setup SSH for storage upload
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan mgmt02-vm-core01.noroutine.me >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install dependencies
        shell: bash
        run: |
          # Install rsync
          sudo apt-get update
          sudo apt-get install -y rsync

          # Install regsync
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          [ "$ARCH" = "x86_64" ] && ARCH=amd64
          [ "$ARCH" = "aarch64" ] && ARCH=arm64
          curl -sSL "https://github.com/regclient/regclient/releases/latest/download/regsync-${OS}-${ARCH}" -o /usr/local/bin/regsync
          sudo chmod +x /usr/local/bin/regsync

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"

      - name: Archive images with infra CLI
        run: |
          uv run infra archive-images \
            --mode "${{ github.event.inputs.mode }}" \
            --registry "${{ env.IMAGE_REGISTRY }}" \
            --namespace infra \
            --version "${{ steps.version.outputs.version }}" \
            --batch-size "${{ github.event.inputs.batch_size }}" \
            --archive-dir ./archive \
            --upload

      - name: Summary
        run: |
          echo "## Archive Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Mode:** \`${{ github.event.inputs.mode }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Registry:** \`${{ env.IMAGE_REGISTRY }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Namespace:** \`infra\`" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ steps.version.outputs.version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Batch size:** \`${{ github.event.inputs.batch_size }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Archive uploaded to: \`oleksii@mgmt02-vm-core01.noroutine.me:/mnt/data/infra/${{ steps.version.outputs.version }}/images\`" >> $GITHUB_STEP_SUMMARY
