name: images
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  IMAGE_REGISTRY: ${{ vars.IMAGE_REGISTRY || 'cr.nrtn.dev' }}

jobs:
  import-images:
    name: import-images
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | base64 -d | ssh-add -

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set INFRA_VERSION
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "infra_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
            echo "infra_namespace=infra" >> $GITHUB_OUTPUT
          else
            echo "infra_version=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
            echo "infra_namespace=infra-dev" >> $GITHUB_OUTPUT
          fi

      - name: Import images with Dagger
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: with-docker-cfg --docker-cfg env://DOCKER_CFG import-images
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_CFG: ${{ secrets.DOCKER_CFG }}

      - name: Generate artifacts with Dagger
        id: generate
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: generate-artifacts --infra-version="${{ steps.version.outputs.infra_version }}" export --path=./artifacts
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Set up SSH and push to GitHub upstream repo
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | base64 -d | ssh-add -

          git clone git@github.com:noroutine/upstream.git upstream
          cd upstream
          cp ../artifacts/Dockerfile .
          cp ../artifacts/infra.json .
          git config user.name "Forgejo Bot"
          git config user.email "bot@forgejo"
          git add Dockerfile infra.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Infra ${{ steps.version.outputs.infra_version }}"
            git push origin master
          fi

          # Tag if we are doing this for a tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            git tag "${{ github.ref_name }}" || true
            git push origin "${{ github.ref_name }}" || true
          fi

    outputs:
      infra_version: ${{ steps.version.outputs.infra_version }}
      infra_namespace: ${{ steps.version.outputs.infra_namespace }}

  archive-images:
    name: archive-images
    runs-on: ubuntu-latest
    needs: import-images
    if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dagger
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"

      - name: Archive images to storage
        run: |
          dagger call \
            with-docker-cfg --docker-cfg env://DOCKER_CFG \
            with-ssh-private-key --ssh-private-key env://SSH_PRIVATE_KEY \
            archive-images-to-storage \
              --infra-bucket="${{ needs.import-images.outputs.infra_version }}"
        env:
          DOCKER_CFG: ${{ secrets.DOCKER_CFG }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  retag-generic-images:
    name: retag-generic-images
    runs-on: ubuntu-latest
    needs: import-images
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker config
        run: |
          mkdir -p ~/.docker
          echo "${{ secrets.DOCKER_CFG }}" | base64 -d > ~/.docker/config.json

      - name: Install yq (cross-platform)
        shell: bash
        run: |
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          [ "$ARCH" = "x86_64" ] && ARCH=amd64
          curl -sSL "https://github.com/mikefarah/yq/releases/latest/download/yq_${OS}_${ARCH}" -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Install crane (cross-platform)
        shell: bash
        run: |
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          [ "$ARCH" = "x86_64" ] && ARCH=x86_64
          curl -sSL "https://github.com/google/go-containerregistry/releases/latest/download/go-containerregistry_${OS}_${ARCH}.tar.gz" -o crane.tar.gz
          tar -xzf crane.tar.gz
          sudo mv crane /usr/local/bin/
          sudo chmod +x /usr/local/bin/crane

      - name: Retag generic images
        run: |
          ./retag.sh \
            --registry "${{ env.IMAGE_REGISTRY }}" \
            --namespace "${{ needs.import-images.outputs.infra_namespace }}" \
            --version "${{ needs.import-images.outputs.infra_version }}" \
            --parallel 10
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INFRA_NAMESPACE: ${{ needs.import-images.outputs.infra_namespace }}
          INFRA_VERSION: ${{ needs.import-images.outputs.infra_version }}

  build-custom-images:
    name: build-custom-images
    runs-on: ubuntu-latest
    needs: import-images
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Docker config
        run: |
          mkdir -p ~/.docker
          echo "${{ secrets.DOCKER_CFG }}" | base64 -d > ~/.docker/config.json

      - name: Install yq (cross-platform)
        shell: bash
        run: |
          OS=$(uname -s | tr '[:upper:]' '[:lower:]')
          ARCH=$(uname -m)
          [ "$ARCH" = "x86_64" ] && ARCH=amd64
          curl -sSL "https://github.com/mikefarah/yq/releases/latest/download/yq_${OS}_${ARCH}" -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Build and push scratch stage
        run: |
          ./build.sh scratch \
            --registry "${{ env.IMAGE_REGISTRY }}" \
            --namespace "${{ needs.import-images.outputs.infra_namespace }}" \
            --version "${{ needs.import-images.outputs.infra_version }}" \
            --push
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INFRA_NAMESPACE: ${{ needs.import-images.outputs.infra_namespace }}
          INFRA_VERSION: ${{ needs.import-images.outputs.infra_version }}

      - name: Build and push base stage
        run: |
          ./build.sh base \
            --registry "${{ env.IMAGE_REGISTRY }}" \
            --namespace "${{ needs.import-images.outputs.infra_namespace }}" \
            --version "${{ needs.import-images.outputs.infra_version }}" \
            --push
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INFRA_NAMESPACE: ${{ needs.import-images.outputs.infra_namespace }}
          INFRA_VERSION: ${{ needs.import-images.outputs.infra_version }}

      - name: Build and push custom stage
        run: |
          ./build.sh custom \
            --registry "${{ env.IMAGE_REGISTRY }}" \
            --namespace "${{ needs.import-images.outputs.infra_namespace }}" \
            --version "${{ needs.import-images.outputs.infra_version }}" \
            --push
        env:
          IMAGE_REGISTRY: ${{ env.IMAGE_REGISTRY }}
          INFRA_NAMESPACE: ${{ needs.import-images.outputs.infra_namespace }}
          INFRA_VERSION: ${{ needs.import-images.outputs.infra_version }}

      - name: Summary
        run: |
          echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Registry:** \`${{ env.IMAGE_REGISTRY }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Namespace:** \`${{ needs.import-images.outputs.infra_namespace }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Version:** \`${{ needs.import-images.outputs.infra_version }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Scratch Stage" >> $GITHUB_STEP_SUMMARY

          # Export variables for docker-compose
          export IMAGE_REGISTRY="${{ env.IMAGE_REGISTRY }}"
          export INFRA_NAMESPACE="${{ needs.import-images.outputs.infra_namespace }}"
          export INFRA_VERSION="${{ needs.import-images.outputs.infra_version }}"

          docker compose -f docker-compose.scratch.yml config --services | while read service; do
            echo "- \`${{ env.IMAGE_REGISTRY }}/${{ needs.import-images.outputs.infra_namespace }}/${service}:${{ needs.import-images.outputs.infra_version }}\`" >> $GITHUB_STEP_SUMMARY
          done

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Base Stage" >> $GITHUB_STEP_SUMMARY

          # Export variables from variables.yml for base compose
          while IFS='=' read -r key value; do
            export "$key=$value"
          done < <(yq eval '.variables | to_entries | .[] | .key + "=" + .value' variables.yml)

          docker compose -f docker-compose.base.yml config --services | while read service; do
            echo "- \`${{ env.IMAGE_REGISTRY }}/${{ needs.import-images.outputs.infra_namespace }}/${service}:${{ needs.import-images.outputs.infra_version }}\`" >> $GITHUB_STEP_SUMMARY
          done

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Custom Stage" >> $GITHUB_STEP_SUMMARY

          docker compose -f docker-compose.custom.yml config --services | while read service; do
            echo "- \`${{ env.IMAGE_REGISTRY }}/${{ needs.import-images.outputs.infra_namespace }}/${service}:${{ needs.import-images.outputs.infra_version }}\`" >> $GITHUB_STEP_SUMMARY
          done

          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Platforms:** linux/amd64, linux/arm64" >> $GITHUB_STEP_SUMMARY
