name: import-images
on:
  push:
    branches: [master]

jobs:
  import-images:
    name: import-images
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY }}'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Call Dagger Function
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: with-docker-cfg --docker-cfg env://DOCKER_CFG import-images
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_CFG: ${{ secrets.DOCKER_CFG }}

  push-artifacts:
    name: push-artifacts
    runs-on: ubuntu-latest
    needs: hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set INFRA_VERSION
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "infra_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "infra_version=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
          fi

      - name: Generate artifacts with Dagger
        id: generate
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: generate-artifacts --infra-version="${{ steps.version.outputs.infra_version }}" export --path=./artifacts
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Set up SSH and push to GitHub upstream repo
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add - <<< '${{ secrets.SSH_PRIVATE_KEY }}'

          git clone git@github.com:noroutine/upstream.git upstream
          cd upstream
          cp ../artifacts/Dockerfile .
          cp ../artifacts/infra.json .
          git config user.name "Forgejo Bot"
          git config user.email "bot@forgejo"
          git add Dockerfile infra.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Infra ${{ steps.version.outputs.infra_version }}"
            git push origin master
          fi

          # Tag if we are doing this for a tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            git tag "${{ github.ref_name }}" || true
            git push origin "${{ github.ref_name }}" || true
          fi