name: import-images
on:
  push:
    branches: [master]

jobs:
  import-images:
    name: import-images
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | base64 -d | ssh-add -

      - name: Checkout
        uses: actions/checkout@v4

      - name: Import images with Dagger
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: with-docker-cfg --docker-cfg env://DOCKER_CFG import-images
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
        env:
          DOCKER_CFG: ${{ secrets.DOCKER_CFG }}

  archive-images:
    name: archive-images
    runs-on: ubuntu-latest
    needs: import-images
    # TODO: Uncomment when ready to archive only on tags
    # if: github.ref_type == 'tag'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set INFRA_VERSION
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "infra_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "infra_version=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
          fi

      - name: Install Dagger
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"

      - name: Archive images to storage
        run: |
          dagger call \
            with-docker-cfg --docker-cfg env://DOCKER_CFG \
            with-ssh-private-key --ssh-private-key env://SSH_PRIVATE_KEY \
            archive-images-to-storage \
              --infra-bucket="${{ steps.version.outputs.infra_version }}"
        env:
          DOCKER_CFG: ${{ secrets.DOCKER_CFG }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DAGGER_CLOUD_TOKEN: ${{ secrets.DAGGER_CLOUD_TOKEN }}

  mirror:
    name: mirror
    runs-on: ubuntu-latest
    needs: import-images
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up SSH and mirror to remotes
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan git.nrtn.dev >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | base64 -d | ssh-add -

          # Mirror to GitHub turbovillains (use --mirror for full mirror)
          git push --mirror --force git@github.com:turbovillains/infra-setup.git

          # Push to GitLab to trigger CI/CD (separate pushes to avoid hidden refs error)
          git push --all --force git@git.nrtn.dev:infra/infra-setup.git
          git push --tags --force git@git.nrtn.dev:infra/infra-setup.git

  push-artifacts:
    name: push-artifacts
    runs-on: ubuntu-latest
    needs: import-images
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set INFRA_VERSION
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "infra_version=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "infra_version=${GITHUB_SHA:0:8}" >> $GITHUB_OUTPUT
          fi

      - name: Generate artifacts with Dagger
        id: generate
        uses: https://github.com/dagger/dagger-for-github@v8.2.0
        with:
          version: "latest"
          args: generate-artifacts --infra-version="${{ steps.version.outputs.infra_version }}" export --path=./artifacts
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Set up SSH and push to GitHub upstream repo
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          echo '${{ secrets.SSH_PRIVATE_KEY }}' | base64 -d | ssh-add -

          git clone git@github.com:noroutine/upstream.git upstream
          cd upstream
          cp ../artifacts/Dockerfile .
          cp ../artifacts/infra.json .
          git config user.name "Forgejo Bot"
          git config user.email "bot@forgejo"
          git add Dockerfile infra.json
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Infra ${{ steps.version.outputs.infra_version }}"
            git push origin master
          fi

          # Tag if we are doing this for a tag
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            git tag "${{ github.ref_name }}" || true
            git push origin "${{ github.ref_name }}" || true
          fi