ARG DOCKER_HUB
ARG VELERO_PLUGIN_CSI_VERSION

FROM ${DOCKER_HUB}/velero/velero-plugin-for-csi:${VELERO_PLUGIN_CSI_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
