ARG DOCKER_HUB
ARG CONFLUENTINC_INIT_CONTAINER_VERSION
FROM ${DOCKER_HUB}/confluentinc/confluent-init-container:${CONFLUENTINC_INIT_CONTAINER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
