ARG DOCKER_HUB
ARG CSI_SNAPSHOT_VALIDATION_WEBHOOK_VERSION

FROM ${DOCKER_HUB}/sig-storage/snapshot-validation-webhook:${CSI_SNAPSHOT_VALIDATION_WEBHOOK_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
