ARG DOCKER_HUB
ARG CSI_SNAPSHOTTER_VERSION

FROM ${DOCKER_HUB}/sig-storage/snapshot-validation-webhook:${CSI_SNAPSHOTTER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
