apiVersion: v1
entries:
  gpu-operator:
  - apiVersion: v2
    appVersion: v24.3.0
    created: "2024-05-24T16:05:53.374528+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.15.4
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: ca3ad7585046897a772f0faf664a1538309886c5687f4652520752f428f0987e
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v24.3.0.tgz
    version: v24.3.0
  - apiVersion: v2
    appVersion: v23.9.2
    created: "2024-05-24T16:05:53.371269+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.14.2
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 9263a5647500d5364ffd91e009e83aa5264861a52f608ce33b247337f5d19593
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.9.2.tgz
    version: v23.9.2
  - apiVersion: v2
    appVersion: v23.9.1
    created: "2024-05-24T16:05:53.36717+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.14.2
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: ac943e278ddd52df24ab74f88a4a7e53622c26469795a24941ac256f81f5c5e8
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.9.1.tgz
    version: v23.9.1
  - apiVersion: v2
    appVersion: v23.9.0
    created: "2024-05-24T16:05:53.362434+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.14.2
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 13d8583b37837188e309c36f5507dfee418640874ca6cb45c65c234b5d2029da
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.9.0.tgz
    version: v23.9.0
  - apiVersion: v2
    appVersion: v23.6.2
    created: "2024-05-24T16:05:53.358163+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.13.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 71ef0c54848dfdef43e2308282b8ff35927e324cc4eaae716a2ce49c9dd14f76
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.6.2.tgz
    version: v23.6.2
  - apiVersion: v2
    appVersion: v23.6.1
    created: "2024-05-24T16:05:53.354633+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.13.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 4ed44779da3cdbcf08de33c377388c44b457d82ce0f110faefe45870b8ae8fb3
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.6.1.tgz
    version: v23.6.1
  - apiVersion: v2
    appVersion: v23.6.0
    created: "2024-05-24T16:05:53.349957+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.13.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: e004bc48bb201e8d045a1af297c7dd397d7cea86f03b3796b30e469cafd779ff
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.6.0.tgz
    version: v23.6.0
  - apiVersion: v2
    appVersion: v23.3.2
    created: "2024-05-24T16:05:53.345932+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.12.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: f8f21e120403fc028d36da4963e2f56add6b9c7adfcf0643f7bded62b009c720
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.3.2.tgz
    version: v23.3.2
  - apiVersion: v2
    appVersion: v23.3.1
    created: "2024-05-24T16:05:53.342195+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.12.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: db8735976a587c4bca666c874e996b528c79472b3e283224b11900339be19321
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.3.1.tgz
    version: v23.3.1
  - apiVersion: v2
    appVersion: v23.3.0
    created: "2024-05-24T16:05:53.337445+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.12.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 6c53bf85c9076b424142a416f5db5df7150b7ee9c60cc27cb3e84012e99ed058
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v23.3.0.tgz
    version: v23.3.0
  - apiVersion: v2
    appVersion: v22.9.2
    created: "2024-05-24T16:05:53.333653+02:00"
    dependencies:
    - condition: nfd.enabled
      name: node-feature-discovery
      repository: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      version: v0.10.1
    description: NVIDIA GPU Operator creates/configures/manages GPUs atop Kubernetes
    digest: 2309c245b8fadff5e65d7dea139a6f962ed8a2cc5b708f3f1531e87c3e509db9
    home: https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/overview.html
    icon: https://assets.nvidiagrid.net/ngc/logos/GPUoperator.png
    keywords:
    - gpu
    - cuda
    - compute
    - operator
    - deep learning
    - monitoring
    - tesla
    kubeVersion: '>= 1.16.0-0'
    name: gpu-operator
    sources:
    - https://github.com/NVIDIA/gpu-operator
    urls:
    - gpu-operator-v22.9.2.tgz
    version: v22.9.2
generated: "2024-05-24T16:05:53.329685+02:00"
