apiVersion: v1
entries:
  actions-runner-controller:
  - apiVersion: v2
    appVersion: 0.27.0
    created: "2023-03-11T18:00:10.272108+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 40f9e67d28a6aa5498c77bfc16339ab75df1e7dae42a438bb153f83348dd41ea
    home: https://github.com/actions/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.22.0.tgz
    version: 0.22.0
  - apiVersion: v2
    appVersion: 0.26.0
    created: "2023-03-11T18:00:10.26555+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 7bcc0638b0d8558bfeb4a4425f3f443fa0b6e093153e5bc17e82b549c6708227
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.21.1.tgz
    version: 0.21.1
  - apiVersion: v2
    appVersion: 0.26.0
    created: "2023-03-11T18:00:10.258496+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 4a8971c3adb54ece18f2ce65ccb0d1acbb47b1435ae53bd188e2ef93b19eacf4
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.21.0.tgz
    version: 0.21.0
  - apiVersion: v2
    appVersion: 0.25.2
    created: "2023-03-11T18:00:10.251392+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 02ff6a41a2a50907370a3a5edc0887e923602b56a07a761d78118b8e80a8795d
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.20.2.tgz
    version: 0.20.2
  - apiVersion: v2
    appVersion: 0.25.1
    created: "2023-03-11T18:00:10.243669+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 7fced32d26d1e924f97fa59a8f6cbcec4d0f79525d70d079ed97a8c28e80a96f
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.20.1.tgz
    version: 0.20.1
  - apiVersion: v2
    appVersion: 0.25.0
    created: "2023-03-11T18:00:10.236733+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: b63305f438b09afe7cdb43d2e0e98fb3b22b853d7d54af2469f17507c61a6f9a
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.20.0.tgz
    version: 0.20.0
  - apiVersion: v2
    appVersion: 0.24.1
    created: "2023-03-11T18:00:10.228683+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 8aa5ff6e3f88e68b20ecbce7225d8ba3059616dfab8e09fb2da78cdd483ff096
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.19.1.tgz
    version: 0.19.1
  - apiVersion: v2
    appVersion: 0.24.0
    created: "2023-03-11T18:00:10.220963+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: eb8cc00658a2916a24177000c9175a746d0dceee881de8cd2bcafc8b086814b1
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.19.0.tgz
    version: 0.19.0
  - apiVersion: v2
    appVersion: 0.23.0
    created: "2023-03-11T18:00:10.21299+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: c2dca18c8f6e9671e64d13485e3456140bad1f1796a0ec09396c0cae4b4100b5
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.18.0.tgz
    version: 0.18.0
  - apiVersion: v2
    appVersion: 0.22.3
    created: "2023-03-11T18:00:10.204896+01:00"
    description: A Kubernetes controller that operates self-hosted runners for GitHub
      Actions on your Kubernetes cluster.
    digest: 46456e7ea5029dfd3d9e80aca56f22f8e3eaad0f05cce7ccece7846d7bde3936
    home: https://github.com/actions-runner-controller/actions-runner-controller
    maintainers:
    - name: actions-runner-controller
      url: https://github.com/actions-runner-controller
    name: actions-runner-controller
    sources:
    - https://github.com/actions-runner-controller/actions-runner-controller
    type: application
    urls:
    - actions-runner-controller-0.17.3.tgz
    version: 0.17.3
generated: "2023-03-11T18:00:10.194788+01:00"
