api = "0.5"

[buildpack]
id = "heroku/nodejs"
version = "0.3.5"
name = "Node.js"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.5"

[[order.group]]
id = "heroku/nodejs-yarn"
version = "0.1.6"

[[order.group]]
id = "heroku/nodejs-typescript"
version = "0.2.4"
optional = true

[[order.group]]
id = "heroku/procfile"
version = "0.6.2"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.7.5"

[[order.group]]
id = "heroku/nodejs-npm"
version = "0.4.5"

[[order.group]]
id = "heroku/nodejs-typescript"
version = "0.2.4"
optional = true

[[order.group]]
id = "heroku/procfile"
version = "0.6.2"
optional = true

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack"
