api = "0.9"

[buildpack]
id = "heroku/nodejs"
version = "0.6.6"
name = "Node.js"
homepage = "https://github.com/heroku/buildpacks-nodejs"

[[buildpack.licenses]]
type = "MIT"

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.8.23"

[[order.group]]
id = "heroku/nodejs-yarn"
version = "0.4.4"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[[order]]

[[order.group]]
id = "heroku/nodejs-engine"
version = "0.8.23"

[[order.group]]
id = "heroku/nodejs-npm"
version = "0.5.4"

[[order.group]]
id = "heroku/procfile"
version = "2.0.0"
optional = true

[metadata]

[metadata.release]

[metadata.release.docker]
repository = "cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack"
