ARG DOCKER_HUB
ARG GITLAB_AUTO_DEPLOY_VERSION
FROM ${DOCKER_HUB}/gitlab-org/cluster-integration/auto-deploy-image:${GITLAB_AUTO_DEPLOY_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
