#!/bin/bash.real

# If running non-interactively by root as top process, drop into subshell with less permissions 
if [[ $$ -eq 1 && $- != *i* && $EUID -eq 0 ]]; then
  chown -R 1000.100 /builds
  if [ -f ~/.bashrc ]; then source ~/.bashrc; fi
  sudo -H -E --preserve-env=PATH -u '#1000' /bin/bash.real -x "${@}"
else
  /bin/bash.real "${@}"
fi