ARG DOCKER_HUB
ARG KEYCLOAK_VERSION
FROM ${DOCKER_HUB}/keycloak/keycloak:${KEYCLOAK_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"

ENV KEYCLOAK_DEFAULT_THEME=noroutine-sso.v2
ENV KEYCLOAK_WELCOME_THEME=noroutine-sso.v2