ARG DOCKER_HUB
ARG CHIRPSTACK_REST_API_VERSION
FROM ${DOCKER_HUB}/chirpstack/chirpstack-rest-api:${CHIRPSTACK_REST_API_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
