ARG DOCKER_HUB
ARG JUPYTERHUB_SCHEDULER_VERSION

FROM ${DOCKER_HUB}/kubernetes/kube-scheduler:${JUPYTERHUB_SCHEDULER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
