ARG DOCKER_HUB
ARG NVIDIA_K8S_DEVICE_PLUGIN_VERSION
FROM ${DOCKER_HUB}/nvidia/k8s-device-plugin:${NVIDIA_K8S_DEVICE_PLUGIN_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
