ARG DOCKER_HUB
ARG VELERO_RESTIC_RESTORE_HELPER_VERSION

FROM ${DOCKER_HUB}/velero/velero-restic-restore-helper:${VELERO_RESTIC_RESTORE_HELPER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
