ARG DOCKER_HUB
ARG GITLAB_CLUSTER_APPLICATIONS_VERSION
FROM ${DOCKER_HUB}/gitlab-org/cluster-integration/cluster-applications:${GITLAB_CLUSTER_APPLICATIONS_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"