ARG DOCKER_HUB
ARG CHIRPSTACK_GATEWAY_BRIDGE_VERSION
FROM ${DOCKER_HUB}/chirpstack/chirpstack-gateway-bridge:${CHIRPSTACK_GATEWAY_BRIDGE_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
