ARG DOCKER_HUB
ARG CONFLUENTINC_OPERATOR_VERSION
FROM ${DOCKER_HUB}/confluentinc/confluent-operator:${CONFLUENTINC_OPERATOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
