ARG DOCKER_HUB
ARG PROMETHEUS_OPERATOR_VERSION
FROM ${DOCKER_HUB}/prometheus-operator/prometheus-config-reloader:${PROMETHEUS_OPERATOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
