ARG DOCKER_HUB
ARG CERT_MANAGER_CAINJECTOR_VERSION
FROM ${DOCKER_HUB}/jetstack/cert-manager-cainjector:${CERT_MANAGER_CAINJECTOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
