ARG DOCKER_HUB
ARG CERT_MANAGER_CSI_DRIVER_VERSION

FROM ${DOCKER_HUB}/jetstack/cert-manager-csi-driver:${CERT_MANAGER_CSI_DRIVER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
