ARG DOCKER_HUB
ARG BITNAMI_GRAFANA_IMAGE_RENDERER_VERSION

FROM ${DOCKER_HUB}/bitnami/grafana-image-renderer:${BITNAMI_GRAFANA_IMAGE_RENDERER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
