ARG DOCKER_HUB
ARG CERT_MANAGER_CONTROLLER_VERSION
FROM ${DOCKER_HUB}/jetstack/cert-manager-controller:${CERT_MANAGER_CONTROLLER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
