ARG DOCKER_HUB
ARG PROMETHEUS_ES_EXPORTER_VERSION
FROM ${DOCKER_HUB}/braedon/prometheus-es-exporter:${PROMETHEUS_ES_EXPORTER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
