ARG DOCKER_HUB
ARG AZURE_SERVICE_OPERATOR_VERSION

FROM ${DOCKER_HUB}/k8s/azureserviceoperator:${AZURE_SERVICE_OPERATOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
