ARG DOCKER_HUB
ARG NVIDIA_K8S_MIG_MANAGER_VERSION
FROM ${DOCKER_HUB}/nvidia/cloud-native/k8s-mig-manager:${NVIDIA_K8S_MIG_MANAGER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
