ARG DOCKER_HUB
ARG CERT_MANAGER_WEBHOOK_VERSION
FROM ${DOCKER_HUB}/jetstack/cert-manager-webhook:${CERT_MANAGER_WEBHOOK_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
