FROM scratch

ADD noroutine noroutine

# full bundle of CA certs set from Mozilla + Noroutine CA certs
ADD ca-certificates.crt .

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
