# https://github.com/heroku/pack-images
# https://github.com/heroku/stack-images
# https://github.com/buildpacks/registry-index
# https://github.com/heroku/buildpacks-nodejs
description = "Base builder for Noroutine Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
id = "heroku-20"
build-image = "cr.nrtn.dev/infra/pack-build:20"
run-image = "cr.nrtn.dev/infra/pack:20"

[lifecycle]
version = "0.13.5"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:1483c15d79e460d8e682f9e1f765a04cca130e43e65ade4390d67fc944c4358a"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack@sha256:39ad34bcc1766cdff4f2a4d5e88931a2f2678f5605bd56f1b6fc551f40fba70f"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://github.com/heroku/heroku-buildpack-ruby/releases/download/v222/heroku-buildpack-ruby-v222.tgz"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://cr.nrtn.dev/heroku/procfile-cnb:1.0.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack:0.3.5"

# [[buildpacks]]
#   id = "heroku/nodejs-function"
#   uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-function-buildpack:0.5.7"

[[buildpacks]]
  id = "noroutine/static"
  uri = "noroutine-static"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.90"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "0.6.2"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.5"

  [[order.group]]
    id = "noroutine/static"
    version = "0.0.3"
    optional = true

# [[order]]
#   [[order.group]]
#     id = "heroku/java-function"
#     version = "0.3.15"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.5"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.10"