# https://github.com/heroku/pack-images
# https://github.com/heroku/stack-images
# https://github.com/buildpacks/registry-index
# https://github.com/heroku/buildpacks-nodejs
description = "Base builder for Noroutine Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
id = "heroku-20"
build-image = "cr.nrtn.dev/infra/pack-build:20"
run-image = "cr.nrtn.dev/infra/pack:20"

[lifecycle]
version = "0.14.2"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-buildpack@sha256:82e235e8c4e5d6d9e0e1e3ba59d8114871565fb2b7df63bcef48d67ecacc09e6"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-scala-buildpack@sha256:02a26d364465a567782806effa2afbf4b992a1e15453bb8e62c5da27118dc7e6"

[[buildpacks]]
  id = "heroku/java-function"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-java-function-buildpack@sha256:a27030592f648d5ef32fe9bcbfe326d435698a748b8fa17b1d43a23fea27ec51"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://public.ecr.aws/heroku-buildpacks/heroku-ruby-buildpack@sha256:3eeb3773cdbd29d4fb0d578f7781fe8c525de73593480e2740b7143262e5bef5"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://cr.nrtn.dev/heroku/procfile-cnb:2.0.0"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.3.1&name=Python"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.3.1&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack:0.5.9"

# [[buildpacks]]
#   id = "heroku/nodejs-function"
#   uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-function-buildpack:0.5.7"

[[buildpacks]]
  id = "noroutine/static"
  uri = "noroutine-static"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.1.3"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.92"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.3.1"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.0"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.9"

  [[order.group]]
    id = "noroutine/static"
    version = "0.0.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java-function"
    version = "0.3.29"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.5.9"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.3.16"