# https://github.com/heroku/pack-images
# https://github.com/heroku/stack-images
# https://github.com/buildpacks/registry-index
# https://github.com/heroku/buildpacks-nodejs
description = "Base builder for Noroutine Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
id = "heroku-20"
build-image = "cr.nrtn.dev/infra/pack-build:20"
run-image = "cr.nrtn.dev/infra/pack:20"

[lifecycle]
version = "0.11.4"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://cr.nrtn.dev/heroku/procfile-cnb:0.6.2"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack:0.3.5"

[[buildpacks]]
  id = "heroku/nodejs-function"
  uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-function-buildpack:0.5.7"

[[buildpacks]]
  id = "noroutine/static"
  uri = "noroutine-static"

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.5"

  [[order.group]]
    id = "noroutine/static"
    version = "0.0.3"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "0.3.5"
