# https://github.com/heroku/pack-images
# https://github.com/heroku/stack-images
# https://github.com/buildpacks/registry-index
# https://github.com/heroku/buildpacks-nodejs
description = "Base builder for Noroutine Heroku-20 stack, based on ubuntu:20.04 base image"

[stack]
id = "heroku-20"
build-image = "cr.nrtn.dev/infra/pack-build:20"
run-image = "cr.nrtn.dev/infra/pack:20"

[lifecycle]
version = "0.19.0"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:3c888077056f93d3ceb7c8a5b3dede3e2b06bfa169a8e3fc7383374b6773265a"

[[buildpacks]]
  id = "heroku/scala"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/scala?version=0.0.0&name=Scala"

[[buildpacks]]
  id = "heroku/gradle"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/gradle?version=0.0.0&name=Gradle"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/ruby?version=0.0.0&name=Ruby"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/procfile-cnb:2.0.1"

[[buildpacks]]
  id = "heroku/python"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/python?version=0.0.0&name=Python"

[[buildpacks]]
  id = "heroku/php"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/php?version=0.0.0&name=PHP"

[[buildpacks]]
  id = "heroku/go"
  uri = "https://cnb-shim.herokuapp.com/v1/heroku/go?version=0.0.0&name=Go"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack:1.1.2"

# [[buildpacks]]
#   id = "heroku/nodejs-function"
#   uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-function-buildpack:1.1.2"

[[buildpacks]]
  id = "noroutine/static"
  uri = "noroutine-static"

[[order]]
  [[order.group]]
    id = "heroku/ruby"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.2"

  [[order.group]]
    id = "noroutine/static"
    version = "0.0.4"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "1.1.2"

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "0.6.11"

# heroku/java previously supported Gradle by mixing in the shimmed heroku/gradle buildpack. When we decided to make a
# clean cut and not have shimmed buildpacks in the CNB repository, support for Gradle in heroku/java was dropped.
# To maintain backwards compatibilty, we have this order definition here that mirrors what was in heroku/java
# previously. It can be removed when the heroku/java CNB supports Gradle again.
[[order]]
  [[order.group]]
    id = "heroku/jvm"
    version = "1.0.10"

  [[order.group]]
    id = "heroku/gradle"
    version = "0.0.0"

  [[order.group]]
    id = "heroku/procfile"
    version = "2.0.1"
    optional = true
