[stack]
id = "heroku-20"
build-image = "cr.nrtn.dev/infra/pack-build:20"
run-image = "cr.nrtn.dev/infra/pack:20"

[lifecycle]
version = "0.11.4"

[[buildpacks]]
  id = "heroku/jvm"
  uri = "https://github.com/heroku/heroku-buildpack-jvm-common/releases/download/v121/heroku-jvm-common-cnb-v121.tgz"

[[buildpacks]]
  id = "heroku/spring-boot"
  uri = "urn:cnb:registry:heroku/spring-boot@0.2.2"

[[order]]
  [[order.group]]
    id = "heroku/jvm"

  [[order.group]]
    id = "heroku/spring-boot"
