ARG DOCKER_HUB
ARG KAFKA_ENTERPRISE_CONTROL_CENTER_VERSION
FROM ${DOCKER_HUB}/confluentinc/cp-enterprise-control-center:${KAFKA_ENTERPRISE_CONTROL_CENTER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
