ARG DOCKER_HUB
ARG K8S_DASHBOARD_METRICS_SCRAPER_VERSION

FROM ${DOCKER_HUB}/kubernetesui/metrics-scraper:${K8S_DASHBOARD_METRICS_SCRAPER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
