ARG DOCKER_HUB
ARG VSPHERE_CSI_DRIVER_VERSION
FROM ${DOCKER_HUB}/cloud-provider-vsphere/csi/release/driver:${VSPHERE_CSI_DRIVER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
