apiVersion: v1
entries:
  mosquitto:
  - apiVersion: v2
    appVersion: 1.6.12
    created: "2025-10-18T12:48:19.923671+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: a396738f2485f4701c054c1fb8d71661e87f53d452fc147a7e3959c926ce2721
    name: mosquitto
    urls:
    - mosquitto-2.4.1.tgz
    version: 2.4.1
  - apiVersion: v2
    appVersion: 1.6.12
    created: "2025-10-18T12:48:19.92228+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: 34dfe6bef42c43ebfe53a1ca4b0a7cd605c9778c81f0cd0352dbdc7e600cfb66
    name: mosquitto
    urls:
    - mosquitto-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    appVersion: 1.6.12
    created: "2025-10-18T12:48:19.920981+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: 1615d93b196f42270824fbbb5b11508d38071acdd6da486446f61ac31b618515
    name: mosquitto
    urls:
    - mosquitto-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    appVersion: 1.6.12
    created: "2025-10-18T12:48:19.919462+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: 6502fbaf810c994828c8c480b1d2d544f971ba35509e0c492ed7c7909ae11343
    name: mosquitto
    urls:
    - mosquitto-2.2.0.tgz
    version: 2.2.0
  - apiVersion: v2
    appVersion: 1.6.12
    created: "2025-10-18T12:48:19.917895+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: dbfc55a662d4cdbc4fe8f00a3599a6330595aa7c462f2c376bc3d98f76aeef54
    name: mosquitto
    urls:
    - mosquitto-2.1.0.tgz
    version: 2.1.0
  - apiVersion: v2
    appVersion: 1.6.12
    created: "2025-10-18T12:48:19.916684+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: ae5784fd89bb832cf791f57380757ec6d215d553fb634d3111bbc0fb772a0eab
    name: mosquitto
    urls:
    - mosquitto-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: "1.6"
    created: "2025-10-18T12:48:19.915563+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: 34e7068e3ce05bb52a5241336e3c283751f438ebfb6283e306f94a5f0af6e384
    name: mosquitto
    urls:
    - mosquitto-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: "1.6"
    created: "2025-10-18T12:48:19.914415+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: 94aa2ee3d144609d31d7acba95bf6ac4492aeaab63fee2d903f5d4732a720776
    name: mosquitto
    urls:
    - mosquitto-1.0.0.tgz
    version: 1.0.0
  - apiVersion: v1
    appVersion: "1.6"
    created: "2025-10-18T12:48:19.913143+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: 2e09888cc12b5d8f0a144aa036d3bed0d0cd4b1768334a4f736028b9c85d254f
    name: mosquitto
    urls:
    - mosquitto-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v1
    appVersion: "1.6"
    created: "2025-10-18T12:48:19.91173+02:00"
    description: Eclipse Mosquitto is an open source message broker which implements
      MQTT version 5, 3.1.1 and 3.1
    digest: d28b8db7cfff292277eee3c067e296a37669dbbee840dbc45641ce3ef6f04573
    name: mosquitto
    urls:
    - mosquitto-0.1.0.tgz
    version: 0.1.0
generated: "2025-10-18T12:48:19.909731+02:00"
