# https://github.com/heroku/pack-images
# https://github.com/heroku/stack-images
# https://github.com/buildpacks/registry-index
# https://github.com/heroku/buildpacks-nodejs
description = "Base builder for Noroutine Heroku-22 stack, based on ubuntu:22.04 base image"

[stack]
id = "heroku-22"
build-image = "heroku/heroku:22-cnb-build"
run-image = "heroku/heroku:22-cnb"

[lifecycle]
version = "0.19.1"

[[buildpacks]]
  id = "heroku/go"
  uri = "docker://docker.io/heroku/buildpack-go@sha256:8123cbeefc05f54c0f4b386bccdc78710d55bc500a99d6b75afd0680d537e016"

[[buildpacks]]
  id = "heroku/java"
  uri = "docker://docker.io/heroku/buildpack-java@sha256:20b9b71a87e94e82d2e3a54e9329af49bce93d61211e4169cfe7b490972cf8d0"

[[buildpacks]]
  id = "heroku/nodejs"
  uri = "docker://docker.io/heroku/buildpack-nodejs@sha256:643a4e4b95099b80f42e06fbdbbfb54b79c53989109510990a6085e41dd3862e"

[[buildpacks]]
  id = "heroku/php"
  uri = "docker://docker.io/heroku/buildpack-php@sha256:9d76792ba9869eb96ba3b41b0bfb48c6adfaa58a361bba6083505c84c5a8d61e"

[[buildpacks]]
  id = "heroku/procfile"
  uri = "docker://docker.io/heroku/buildpack-procfile@sha256:1995d5e70d12b928172a09b11ab7b0c07da7857588e743b0e55d4be0d1a59fbf"

[[buildpacks]]
  id = "heroku/python"
  uri = "docker://docker.io/heroku/buildpack-python@sha256:9c57ecaf8695d0dc9b3d2cd9d29384113cfbce26dd0ed31410ac680c4e01c62c"

[[buildpacks]]
  id = "heroku/ruby"
  uri = "docker://docker.io/heroku/buildpack-ruby@sha256:995e2898a7a7fe1cb38ac24263d2f7d3fba1051ce170033320116a8aa81f9b21"

[[buildpacks]]
  id = "heroku/scala"
  uri = "docker://docker.io/heroku/buildpack-scala@sha256:dcf51d14112e5b97cf2f7e1cd19dd89e4850762080dc29c80623c02413ca6e6f"

# [[buildpacks]]
#   id = "heroku/procfile"
#   uri = "docker://docker.io/heroku/buildpack-procfile:3.0.1"

# [[buildpacks]]
#   id = "heroku/nodejs"
#   uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-buildpack:1.1.2"

# [[buildpacks]]
#   id = "heroku/nodejs-function"
#   uri = "docker://cr.nrtn.dev/heroku-buildpacks/heroku-nodejs-function-buildpack:1.1.2"

[[buildpacks]]
  id = "noroutine/static"
  uri = "noroutine-static"

[[order]]
  [[order.group]]
    id = "heroku/python"
    version = "0.8.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/nodejs-engine"
    version = "3.0.1"
    optional = true
  [[order.group]]
    id = "heroku/nodejs-yarn"
    version = "3.0.1"
    optional = true
  [[order.group]]
    id = "heroku/jvm"
    version = "4.1.0"
    optional = true
  [[order.group]]
    id = "heroku/ruby"
    version = "2.1.3"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true


[[order]]
  [[order.group]]
    id = "heroku/nodejs"
    version = "3.0.1"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true
  [[order.group]]
    id = "noroutine/static"
    version = "0.0.5"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/java"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/scala"
    version = "4.1.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/go"
    version = "0.2.0"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true

[[order]]
  [[order.group]]
    id = "heroku/php"
    version = "0.1.2"
  [[order.group]]
    id = "heroku/procfile"
    version = "3.0.1"
    optional = true
