apiVersion: v1
entries:
  mail:
  - apiVersion: v2
    appVersion: 4.1.0
    created: "2024-03-31T15:26:34.119693+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: f54f20ecb3c0fd7bf5aaad6c75ab577b0c0b6ffe2ff937506a975a7a7a8e5907
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-4.1.0.tgz
    version: 4.1.0
  - apiVersion: v2
    appVersion: 4.0.4
    created: "2024-03-31T15:26:34.117615+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 4a02e663a44e4af77d9d11eb2ef9e5ce0a2e63dca89dfe0a58e5ab981637f30a
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-4.0.4.tgz
    version: 4.0.4
  - apiVersion: v2
    appVersion: 4.0.3
    created: "2024-03-31T15:26:34.116226+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 750b7d10f9cc9cbd73fee8be6b083e042a21cdb05e9c4b82aa96ce6e44e7d794
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-4.0.3.tgz
    version: 4.0.3
  - apiVersion: v2
    appVersion: 4.0.2
    created: "2024-03-31T15:26:34.114972+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 6d9e2f74de0ff02f058c5ae27e6c0a43e546468bd249f9409f505b2bc83cde91
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-4.0.2.tgz
    version: 4.0.2
  - apiVersion: v2
    appVersion: 4.0.1
    created: "2024-03-31T15:26:34.113729+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 869b663551188263152185fe53b9937908d68862edc6c199d841cba0c04d0b40
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-4.0.1.tgz
    version: 4.0.1
  - apiVersion: v2
    appVersion: 4.0.0
    created: "2024-03-31T15:26:34.112493+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 4b155286ae9ce750d31eb296dd114e2af6ed2c2d3082546d28bd16dc1996e5ba
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-4.0.0.tgz
    version: 4.0.0
  - apiVersion: v2
    appVersion: v3.6.1
    created: "2024-03-31T15:26:34.123535+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 1885a04a7c16d6358cc25fff18d25c67365efb521437e697523685c214db9e16
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-v3.6.1.tgz
    version: v3.6.1
  - apiVersion: v2
    appVersion: v3.5.1
    created: "2024-03-31T15:26:34.122594+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: eacaf55454e58bfbd9335b81b8ed3e5de739123d62ba7e63ec3e4d0fc804ef21
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-v3.5.1.tgz
    version: v3.5.1
  - apiVersion: v2
    appVersion: v3.5.0
    created: "2024-03-31T15:26:34.121621+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: ac2f5b7f0fdc958ce9a9ff154d8d6a29dc4c8ef07728a29ce91d8941b19363bf
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-v3.5.0.tgz
    version: v3.5.0
  - apiVersion: v2
    appVersion: v3.4.0
    created: "2024-03-31T15:26:34.120659+02:00"
    description: An outgoing SMTP mail relay for your applications in Kubernetes cluster
    digest: 9ede715457bb59579a030682b5eac2fd8b12f6afe26bcf6c00c09535ada4bd3d
    home: https://github.com/bokysan/docker-postfix
    icon: https://bokysan.github.io/docker-postfix/postfix.png
    maintainers:
    - name: Bokysan
      url: https://github.com/bokysan
    name: mail
    sources:
    - https://github.com/bokysan/docker-postfix
    type: application
    urls:
    - mail-v3.4.0.tgz
    version: v3.4.0
generated: "2024-03-31T15:26:34.111036+02:00"
