ARG DOCKER_HUB
ARG VELERO_PLUGIN_AZURE_VERSION

FROM ${DOCKER_HUB}/velero/velero-plugin-for-microsoft-azure:${VELERO_PLUGIN_AZURE_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
