ARG DOCKER_HUB
ARG KAFKA_SCHEMA_REGISTRY_VERSION
FROM ${DOCKER_HUB}/confluentinc/cp-schema-registry:${KAFKA_SCHEMA_REGISTRY_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
