ARG DOCKER_HUB
ARG NVIDIA_K8S_CONTAINER_TOOLKIT_VERSION
FROM ${DOCKER_HUB}/nvidia/k8s/container-toolkit:${NVIDIA_K8S_CONTAINER_TOOLKIT_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
