ARG DOCKER_HUB
ARG NVIDIA_GPU_OPERATOR_VALIDATOR_VERSION
FROM ${DOCKER_HUB}/nvidia/cloud-native/gpu-operator-validator:${NVIDIA_GPU_OPERATOR_VALIDATOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
