ARG DOCKER_HUB
ARG CSI_NODE_DRIVER_REGISTRAR_VERSION
FROM ${DOCKER_HUB}/sig-storage/csi-node-driver-registrar:${CSI_NODE_DRIVER_REGISTRAR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
