ARG DOCKER_HUB
ARG AZURE_WORKLOAD_IDENTITY_VERSION

FROM ${DOCKER_HUB}/oss/azure/workload-identity/webhook:${AZURE_WORKLOAD_IDENTITY_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
