ARG DOCKER_HUB
ARG JENKINS_OPERATOR_VERSION

FROM ${DOCKER_HUB}/jenkins-kubernetes-operator/operator:${JENKINS_OPERATOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
