ARG DOCKER_HUB
ARG BITNAMI_KUBE_RBAC_PROXY_VERSION

FROM ${DOCKER_HUB}/bitnami/kube-rbac-proxy:${BITNAMI_KUBE_RBAC_PROXY_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
