ARG DOCKER_HUB
ARG BLACKBOX_EXPORTER_VERSION
FROM ${DOCKER_HUB}/prometheus/blackbox-exporter:${BLACKBOX_EXPORTER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
