apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    created: "2024-04-01T01:53:05.743858+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: bd0e9510fcc70fe667acd3b4ab0af4ffa0b565f1c3c7ea10079f80f67021ce75
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v2
    created: "2024-04-01T01:53:05.742788+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 3ab9fb577d937c0c03ddd36a17b3d0b0f49467f8cda8e98bb19387fcb638d9d2
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v2
    created: "2024-04-01T01:53:05.740905+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 34a88ef5fc289388beca10bebc74f86f39476e3ecd06f776e81b62e8444993a1
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    created: "2024-04-01T01:53:05.739625+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 56268d4017c66bb355fc0fe60efb103bc6410a1875fcd9f154067a7bbcbca0b2
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    created: "2024-04-01T01:53:05.747502+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: d6d5f069c95df77c734df2fb346243a50863ef867acb7c31f045c5b52ff0a033
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.2.0.tgz
    version: v2.2.0
  - apiVersion: v2
    created: "2024-04-01T01:53:05.745737+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 3a056c39886ffb369cb02cb4f2ca8a6c93c629656bb7191910c0baf55fbad9a4
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.1.0.tgz
    version: v2.1.0
  - apiVersion: v2
    created: "2024-04-01T01:53:05.744722+02:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: d344651f48b66d08fb791f10e309743c4e5cfa520080d59875054e4ef18481b9
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0.tgz
    version: v2.0.0
generated: "2024-04-01T01:53:05.738184+02:00"
