apiVersion: v1
entries:
  azure-service-operator:
  - apiVersion: v2
    created: "2024-11-02T14:14:24.54188+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 3eefa8b982a5887ba2cb7bf3c34328bfa414a6f62944dac4ee8b03162b5b08bc
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.10.0.tgz
    version: 2.10.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.550085+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: ca9048ae6357130188b40d1fb4383288eec656b7a4b97d922642a4a48e3386ef
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.9.0.tgz
    version: 2.9.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.54898+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: f619cf26d01ef80e165be99aab49f03f0b652dd4602fa3349c02f634f1c4ed2a
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.8.0.tgz
    version: 2.8.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.547943+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: c9b31b9e20483fb6c21ab1addecbe9746bb7cd95c575b4e21eb2ddf687f9d665
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.7.0.tgz
    version: 2.7.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.546693+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: bd0e9510fcc70fe667acd3b4ab0af4ffa0b565f1c3c7ea10079f80f67021ce75
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.6.0.tgz
    version: 2.6.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.545619+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 3ab9fb577d937c0c03ddd36a17b3d0b0f49467f8cda8e98bb19387fcb638d9d2
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.5.0.tgz
    version: 2.5.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.544652+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 34a88ef5fc289388beca10bebc74f86f39476e3ecd06f776e81b62e8444993a1
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.4.0.tgz
    version: 2.4.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.543227+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 56268d4017c66bb355fc0fe60efb103bc6410a1875fcd9f154067a7bbcbca0b2
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-2.3.0.tgz
    version: 2.3.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.552878+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: d6d5f069c95df77c734df2fb346243a50863ef867acb7c31f045c5b52ff0a033
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.2.0.tgz
    version: v2.2.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.552201+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: 3a056c39886ffb369cb02cb4f2ca8a6c93c629656bb7191910c0baf55fbad9a4
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.1.0.tgz
    version: v2.1.0
  - apiVersion: v2
    created: "2024-11-02T14:14:24.550972+01:00"
    description: Deploy components and dependencies of azure-service-operator
    digest: d344651f48b66d08fb791f10e309743c4e5cfa520080d59875054e4ef18481b9
    home: https://github.com/Azure/azure-service-operator/v2
    name: azure-service-operator
    sources:
    - https://github.com/Azure/azure-service-operator/v2
    urls:
    - azure-service-operator-v2.0.0.tgz
    version: v2.0.0
generated: "2024-11-02T14:14:24.540916+01:00"
