ARG DOCKER_HUB
ARG VSPHERE_CSI_SYNCER_VERSION
FROM ${DOCKER_HUB}/cloud-provider-vsphere/csi/release/syncer:${VSPHERE_CSI_SYNCER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
