ARG DOCKER_HUB
ARG HARBOR_VERSION
ARG HARBOR_COMPONENT

FROM ${DOCKER_HUB}/goharbor/${HARBOR_COMPONENT}:${HARBOR_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
