ARG DOCKER_HUB
ARG CERT_MANAGER_WEBHOOK_PDNS_VERSION
FROM ${DOCKER_HUB}/zachomedia/cert-manager-webhook-pdns:${CERT_MANAGER_WEBHOOK_PDNS_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
