apiVersion: v1
entries:
  cert-manager:
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 1020CF3C033D4F35BAE1C19E1226061C665DF13E
        url: https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
    apiVersion: v1
    appVersion: v1.14.4
    created: "2024-03-31T15:26:35.487294+02:00"
    description: A Helm chart for cert-manager
    digest: 5775fdbc1881d6e510df76d38753af54b86bd14caa8edb28fdbb79527042dede
    home: https://github.com/cert-manager/cert-manager
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/d53c0b9270f8cd90d908460d69502694e1838f5f/logo/logo-small.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    kubeVersion: '>= 1.22.0-0'
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager
    sources:
    - https://github.com/cert-manager/cert-manager
    urls:
    - cert-manager-v1.14.4.tgz
    version: v1.14.4
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 1020CF3C033D4F35BAE1C19E1226061C665DF13E
        url: https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
    apiVersion: v1
    appVersion: v1.14.3
    created: "2024-03-31T15:26:35.482543+02:00"
    description: A Helm chart for cert-manager
    digest: 3126d0253ec8b0456e0db924cc3e71b24e51f1e66914218ca39ebb606aff0438
    home: https://github.com/cert-manager/cert-manager
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/d53c0b9270f8cd90d908460d69502694e1838f5f/logo/logo-small.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    kubeVersion: '>= 1.22.0-0'
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager
    sources:
    - https://github.com/cert-manager/cert-manager
    urls:
    - cert-manager-v1.14.3.tgz
    version: v1.14.3
  - annotations:
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "false"
      artifacthub.io/signKey: |
        fingerprint: 1020CF3C033D4F35BAE1C19E1226061C665DF13E
        url: https://cert-manager.io/public-keys/cert-manager-keyring-2021-09-20-1020CF3C033D4F35BAE1C19E1226061C665DF13E.gpg
    apiVersion: v1
    appVersion: v1.14.2
    created: "2024-03-31T15:26:35.47873+02:00"
    description: A Helm chart for cert-manager
    digest: 45c13a8a3b0cceea09301bb6f847a8b0ffdc975ed56975e895ac85c651bcde5c
    home: https://github.com/cert-manager/cert-manager
    icon: https://raw.githubusercontent.com/cert-manager/cert-manager/d53c0b9270f8cd90d908460d69502694e1838f5f/logo/logo-small.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    kubeVersion: '>= 1.22.0-0'
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager
    sources:
    - https://github.com/cert-manager/cert-manager
    urls:
    - cert-manager-v1.14.2.tgz
    version: v1.14.2
  - apiVersion: v1
    appVersion: v0.16.1
    created: "2024-03-31T15:26:35.474668+02:00"
    description: A Helm chart for cert-manager
    digest: 690a2c066fd823e39115b46568ac1c24c5fd46d290fead4c2572636b45d260f3
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.16.1.tgz
    version: v0.16.1
  - apiVersion: v1
    appVersion: v0.16.0
    created: "2024-03-31T15:26:35.468824+02:00"
    description: A Helm chart for cert-manager
    digest: fb0f13bed040e565e5cacbef41a25c551b0b2dc0383f0cb87cf30d27408b198e
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.16.0.tgz
    version: v0.16.0
  - apiVersion: v1
    appVersion: v0.15.2
    created: "2024-03-31T15:26:35.461657+02:00"
    description: A Helm chart for cert-manager
    digest: ee1b94d9e2c679a6284669749f7186f5ded227a4675488aebfdd491efbdbfcec
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.15.2.tgz
    version: v0.15.2
  - apiVersion: v1
    appVersion: v0.15.1
    created: "2024-03-31T15:26:35.458418+02:00"
    description: A Helm chart for cert-manager
    digest: f446f7a24ea0be194dced2842d9aef2419ba68eca8d43f3060bc88f72844fe94
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.15.1.tgz
    version: v0.15.1
  - apiVersion: v1
    appVersion: v0.15.0
    created: "2024-03-31T15:26:35.454101+02:00"
    description: A Helm chart for cert-manager
    digest: 9ac0ac003cb5ddf6bbf8836fc52f300b974e5c1d5870cbe30553f5ea330fd1a4
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.15.0.tgz
    version: v0.15.0
  - apiVersion: v1
    appVersion: v0.14.3
    created: "2024-03-31T15:26:35.449899+02:00"
    description: A Helm chart for cert-manager
    digest: 3563c03a7c2433167b5f5a3f10df7a21ebc9cc31cc9f99153a06edc3fde242b6
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.14.3.tgz
    version: v0.14.3
  - apiVersion: v1
    appVersion: v0.14.2
    created: "2024-03-31T15:26:35.448954+02:00"
    description: A Helm chart for cert-manager
    digest: 160e1bd4906855b91c8ba42afe10af2d0443b184916e4534175890b1a7278f4e
    home: https://github.com/jetstack/cert-manager
    icon: https://raw.githubusercontent.com/jetstack/cert-manager/master/logo/logo.png
    keywords:
    - cert-manager
    - kube-lego
    - letsencrypt
    - tls
    maintainers:
    - email: james@jetstack.io
      name: munnerz
    name: cert-manager
    sources:
    - https://github.com/jetstack/cert-manager
    urls:
    - cert-manager-v0.14.2.tgz
    version: v0.14.2
  cert-manager-csi-driver:
  - annotations:
      artifacthub.io/alternativeName: csi-driver
      artifacthub.io/category: security
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "false"
      artifacthub.io/recommendations: |
        - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager-csi-driver-spiffe
        - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
        - url: https://artifacthub.io/packages/helm/cert-manager/trust-manager
    apiVersion: v2
    appVersion: v0.8.0
    created: "2024-03-31T15:26:35.448034+02:00"
    description: cert-manager csi-driver enables issuing secretless X.509 certificates
      for pods using cert-manager
    digest: feced68fbde57c5b54384c77155547a13f39a33c612b9e49a49dcb91b0617b15
    home: https://cert-manager.io/docs/usage/csi-driver
    icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
    keywords:
    - cert-manager
    - csi
    - tls
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.8.0.tgz
    version: v0.8.0
  - annotations:
      artifacthub.io/alternativeName: csi-driver
      artifacthub.io/category: security
      artifacthub.io/license: Apache-2.0
      artifacthub.io/prerelease: "false"
      artifacthub.io/recommendations: |
        - url: https://artifacthub.io/packages/helm/cert-manager/csi-driver-spiffe
        - url: https://artifacthub.io/packages/helm/cert-manager/cert-manager
        - url: https://artifacthub.io/packages/helm/cert-manager/trust-manager
    apiVersion: v2
    appVersion: v0.7.1
    created: "2024-03-31T15:26:35.447375+02:00"
    description: cert-manager csi-driver enables issuing secretless X.509 certificates
      for pods using cert-manager
    digest: 0a74ad7fd439f1f3e6801ff270f1e0776b2afa62be889f34aa752b600a8f4bea
    home: https://cert-manager.io/docs/usage/csi-driver
    icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
    keywords:
    - cert-manager
    - csi
    - tls
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.7.1.tgz
    version: v0.7.1
  - annotations:
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: v0.7.0
    created: "2024-03-31T15:26:35.44675+02:00"
    description: cert-manager-csi-driver enables issuing secretless X.509 certificates
      for pods using cert-manager
    digest: ad29c0f7277495978b9b407f2a47dec843b4f418dfdd16e6e990cd44f4672c42
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.7.0.tgz
    version: v0.7.0
  - apiVersion: v2
    appVersion: v0.6.0
    created: "2024-03-31T15:26:35.446243+02:00"
    description: cert-manager-csi-driver enables issuing secretless X.509 certificates
      for pods using cert-manager
    digest: 10e938d3cc27919970d19871c1f2da2e591a6a85630979e2166600c88d3f4946
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.6.0.tgz
    version: v0.6.0
  - apiVersion: v1
    appVersion: v0.5.0
    created: "2024-03-31T15:26:35.445763+02:00"
    description: A Helm chart for cert-manager-csi-driver
    digest: 704eb568b7e24f576143a29e6749e9a8ea4e9ed2afd47bd99e11d0bd0a372701
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.5.0.tgz
    version: v0.5.0
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2024-03-31T15:26:35.445317+02:00"
    description: A Helm chart for cert-manager-csi-driver
    digest: 322eda26e207123a799064830c3e1150b986cf118ec488316ccf6ced70a29742
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.4.2.tgz
    version: v0.4.2
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2024-03-31T15:26:35.444858+02:00"
    description: A Helm chart for cert-manager-csi-driver
    digest: 763f5d451e9c2abc0ddbadca6d6bd94265ad486642c50c0c580c78d6bf92b846
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.4.1.tgz
    version: v0.4.1
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2024-03-31T15:26:35.444411+02:00"
    description: A Helm chart for cert-manager-csi-driver
    digest: 2969b917f5f0d2934676a228f8cc35a53a50103c9fcc237316770af090af9036
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.4.0.tgz
    version: v0.4.0
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2024-03-31T15:26:35.443944+02:00"
    description: A Helm chart for cert-manager-csi-driver
    digest: c1cf33f18b29b1de8a9ff1f234db450f87f1e562ea52ca7880cd2ec2953907fc
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.3.2.tgz
    version: v0.3.2
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2024-03-31T15:26:35.443478+02:00"
    description: A Helm chart for cert-manager-csi-driver
    digest: 21d36e52e02ec49d13ef14bed45fd51afdcd897b1edda2ab8eaa10e431be7e73
    home: https://github.com/cert-manager/csi-driver
    maintainers:
    - email: cert-manager-maintainers@googlegroups.com
      name: cert-manager-maintainers
      url: https://cert-manager.io
    name: cert-manager-csi-driver
    sources:
    - https://github.com/cert-manager/csi-driver
    type: application
    urls:
    - cert-manager-csi-driver-v0.3.1.tgz
    version: v0.3.1
generated: "2024-03-31T15:26:35.442784+02:00"
