apiVersion: v1
entries:
  strimzi-kafka-operator:
  - apiVersion: v2
    appVersion: 0.48.0
    created: "2025-10-17T12:07:09.538711+02:00"
    description: 'Strimzi: Apache Kafka running on Kubernetes'
    digest: 158ae5d1a72fa01fbef8e070d2531e75c5aa321d26bb149c59b771e9380cbff0
    home: https://strimzi.io/
    icon: https://raw.githubusercontent.com/strimzi/strimzi-kafka-operator/main/documentation/logo/strimzi_logo.png
    keywords:
    - kafka
    - queue
    - stream
    - event
    - messaging
    - datastore
    - topic
    maintainers:
    - email: cncf-strimzi-maintainers@lists.cncf.io
      name: Strimzi Project Maintainers
      url: https://github.com/strimzi/governance
    name: strimzi-kafka-operator
    sources:
    - https://github.com/strimzi/strimzi-kafka-operator
    urls:
    - strimzi-kafka-operator-0.48.0.tgz
    version: 0.48.0
generated: "2025-10-17T12:07:09.533569+02:00"
