ARG DOCKER_HUB
ARG NEXTCLOUD_VERSION

FROM ${DOCKER_HUB}/nextcloud:${NEXTCLOUD_VERSION}

# RUN set -ex; \
#     \
#     sed -i '/^\([^#].*main\)/s/main/& contrib non-free/' /etc/apt/sources.list; \
#     apt-get update; \
#     apt-get install -y --no-install-recommends \
#         php-smbclient \
#     ; \
#     rm -rf /var/lib/apt/lists/*;

MAINTAINER Noroutine GmbH <info@noroutine.me>
