ARG DOCKER_HUB
ARG KAFKA_KSQLDB_SERVER_VERSION
FROM ${DOCKER_HUB}/confluentinc/cp-ksqldb-server:${KAFKA_KSQLDB_SERVER_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
