ARG DOCKER_HUB
ARG NVIDIA_GPU_FEATURE_DISCOVERY_VERSION
FROM ${DOCKER_HUB}/nvidia/gpu-feature-discovery:${NVIDIA_GPU_FEATURE_DISCOVERY_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
