apiVersion: v1
entries:
  gitlab-agent:
  - apiVersion: v2
    appVersion: v16.10.1
    created: "2024-03-31T15:26:34.906998+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 2f55b9689d2739683102eaefe5271584eb4990d5049700e4dc887336981611ee
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.25.0.tgz
    version: 1.25.0
  - apiVersion: v2
    appVersion: v16.9.3
    created: "2024-03-31T15:26:34.905489+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 034b480a0d8b4f0de451fbbc10b86f64762d2b2cf1f13a277e89137608d77f52
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.24.0.tgz
    version: 1.24.0
  - apiVersion: v2
    appVersion: v16.8.0
    created: "2024-03-31T15:26:34.904716+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 754beddce02d5fe36583d7c3be8afe32f72267fac41634ff1e64362b262a6a9f
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.23.0.tgz
    version: 1.23.0
  - apiVersion: v2
    appVersion: v16.7.0
    created: "2024-03-31T15:26:34.903991+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 49554ca7e62bd353cdd726b8a80ace508cc332d44f57f6c8e96ba2feac7805ba
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.22.0.tgz
    version: 1.22.0
  - apiVersion: v2
    appVersion: v16.6.0
    created: "2024-03-31T15:26:34.903361+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: ca277e80081626d8ec00e33e62ca1a96b37a1f8113ea4d5ba15f09ebaa03de0c
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.21.0.tgz
    version: 1.21.0
  - apiVersion: v2
    appVersion: v16.5.0
    created: "2024-03-31T15:26:34.902712+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: a06793adf8331167c2430141a4deb089454696a83ed98722427210adcd0ecb3f
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.20.0.tgz
    version: 1.20.0
  - apiVersion: v2
    appVersion: v16.4.0
    created: "2024-03-31T15:26:34.902057+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 1c73a342f7ec12903da2646036df114afc769bc63993fc65f808ecce37cf77f7
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.19.0.tgz
    version: 1.19.0
  - apiVersion: v2
    appVersion: v16.3.0
    created: "2024-03-31T15:26:34.901408+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 292605bffbccd5068eaebb2949e2b5fe2d447bab5deea1fe743a38269785f8c6
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.18.1.tgz
    version: 1.18.1
  - apiVersion: v2
    appVersion: v16.3.0
    created: "2024-03-31T15:26:34.900737+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 69a6f8ae5bfc20b1de1cf25f8ab8ccd864411cea679c042cb07edb55c200833f
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.18.0.tgz
    version: 1.18.0
  - apiVersion: v2
    appVersion: v16.2.0
    created: "2024-03-31T15:26:34.900034+02:00"
    description: GitLab Agent for Kubernetes is a way to integrate your cluster with
      GitLab in a secure way.
    digest: 344c664ca4d0065edbfc2a5ced53abc3d9197781c4079ff68db605aa3c2b3e3f
    home: https://gitlab.com/gitlab-org/charts/gitlab-agent
    icon: https://gitlab.com/uploads/-/system/project/avatar/34907799/kubernetes-agent.png?width=128
    name: gitlab-agent
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-agent
    - https://gitlab.com/gitlab-org/cluster-integration/gitlab-agent
    type: application
    urls:
    - gitlab-agent-1.17.2.tgz
    version: 1.17.2
  gitlab-runner:
  - apiVersion: v1
    appVersion: 16.10.0
    created: "2024-03-31T15:26:34.919769+02:00"
    description: GitLab Runner
    digest: 55d26d2768d8b10dd485d68c8d479fb8e29bfc8fe0b0fd16eeb91424e1bedfb5
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.63.0.tgz
    version: 0.63.0
  - apiVersion: v1
    appVersion: 16.9.1
    created: "2024-03-31T15:26:34.918605+02:00"
    description: GitLab Runner
    digest: 767c7a8f6e7851dd3e194392fbfc1f6068b788e588d5621d893530c4b145ff56
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.62.1.tgz
    version: 0.62.1
  - apiVersion: v1
    appVersion: 16.9.0
    created: "2024-03-31T15:26:34.917411+02:00"
    description: GitLab Runner
    digest: 489d832ac699a950f4f1659c1cb6cc0127ca36eb506e04ded5cd2170a5a6d840
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.62.0.tgz
    version: 0.62.0
  - apiVersion: v1
    appVersion: 16.8.1
    created: "2024-03-31T15:26:34.915422+02:00"
    description: GitLab Runner
    digest: ef306ac38418df91f5fd3eae95c2f71c323a311acf5f0b8c4e42fe0a1f59d832
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.61.3.tgz
    version: 0.61.3
  - apiVersion: v1
    appVersion: 16.8.0
    created: "2024-03-31T15:26:34.914039+02:00"
    description: GitLab Runner
    digest: 321e7d563ca4dab8fa5ac228ec5a5c98f4c64d198559eb215c604218b79b9133
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.61.2.tgz
    version: 0.61.2
  - apiVersion: v1
    appVersion: 16.8.0
    created: "2024-03-31T15:26:34.912946+02:00"
    description: GitLab Runner
    digest: 041e83185990ec50b61b2a9530b5a1385d34b875170bd7a4a978e949fa4e2660
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.61.1.tgz
    version: 0.61.1
  - apiVersion: v1
    appVersion: 16.8.0
    created: "2024-03-31T15:26:34.911842+02:00"
    description: GitLab Runner
    digest: 26acbb7c924c421b737ab982e526c9516413230b37c36a078a13dc13130ce9ed
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.61.0.tgz
    version: 0.61.0
  - apiVersion: v1
    appVersion: 16.7.1
    created: "2024-03-31T15:26:34.910709+02:00"
    description: GitLab Runner
    digest: 6fac090276b9378c02ae2a63d0abdb00aa377466aac8e10e7a8066a06a8141fb
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.60.1.tgz
    version: 0.60.1
  - apiVersion: v1
    appVersion: 16.7.0
    created: "2024-03-31T15:26:34.909464+02:00"
    description: GitLab Runner
    digest: 20c5ae728363c7b61836031e4f9db7db8d92d9c66ed5910cb591e50b54604633
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.60.0.tgz
    version: 0.60.0
  - apiVersion: v1
    appVersion: 16.6.2
    created: "2024-03-31T15:26:34.908246+02:00"
    description: GitLab Runner
    digest: e4c12fb99ac3756a3f3afa0d0769fcdf5ed1ebc7b91fa4c004c0b4348532b8af
    icon: https://gitlab.com/uploads/-/system/project/avatar/250833/runner_logo.png
    keywords:
    - git
    - ci
    - deploy
    maintainers:
    - email: support@gitlab.com
      name: GitLab Inc.
    name: gitlab-runner
    sources:
    - https://gitlab.com/gitlab-org/charts/gitlab-runner
    - https://gitlab.com/gitlab-org/gitlab-runner
    - https://docs.gitlab.com/runner/
    urls:
    - gitlab-runner-0.59.3.tgz
    version: 0.59.3
generated: "2024-03-31T15:26:34.899199+02:00"
