ARG DOCKER_HUB
ARG EXTERNAL_SECRETS_VERSION
FROM ${DOCKER_HUB}/external-secrets/external-secrets:${EXTERNAL_SECRETS_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.me>"
