ARG DOCKER_HUB
ARG NATS_SERVER_CONFIG_RELOADER

FROM ${DOCKER_HUB}/natsio/nats-server-config-reloader:${NATS_SERVER_CONFIG_RELOADER}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
