ARG DOCKER_HUB
ARG VELERO_PLUGIN_VSPHERE_VERSION

FROM ${DOCKER_HUB}/vsphereveleroplugin/velero-plugin-for-vsphere:${VELERO_PLUGIN_VSPHERE_VERSION}

LABEL org.opencontainers.image.authors="Noroutine GmbH <info@noroutine.com>"
